name: Merge upstream

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight
  workflow_dispatch:

concurrency:
  group: "merge-upstream"
  cancel-in-progress: false

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge upstream
        run: |
          git remote add upstream https://github.com/actions/runner
          git fetch upstream
          git merge --no-edit upstream/main
          git push origin main

  release:
    needs: merge-upstream
    uses: ./.github/workflows/release.yml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
